
language: java
	jdk: oraclejdk8

install:
  - mvn install
	- sudu apt-get update
	
stages:
  - build
  - test

stage: build
script:
  - echo "building"
  - mvn compile


stage: test
script:
 -echo "testing"  


	