language: java
jdk: oraclejdk8
install:
  - shippable_retry mvn install
  
stages:
  - build
  - test
build: null
stage: build
script:
  - echo "building"
  - mvn compile
test:
  stage: test
  script:
    - echo "testing"



	

	
