language: java
jdk: oraclejdk8
install:
  - shippable_retry mvn install
stages:
  - build
  - test
  
build:
stage: build
script:
   - mvn install
   - mvn compile
   - mkdir -p ct417/testResults
   - mkdir -p ct417/codeCoverage
   - cp -r target ct417/codeCoverage
artifacts:
  reports:
     junit:
       - target/surefire-reports/TEST-*.xml
  
test:
  stage: test
  script:
    - echo "testing"
    - mvn test