language: java
jdk: oraclejdk8
install:
  - shippable_retry mvn install
stages:
  - build
  - post_ci
  
build:
stage: build
script:
   - mvn compile
   - mkdir -p ct417/testResults
   - mkdir -p ct417/codeCoverage
   - cp -r target ct417/codeCoverage
   - mvn -Dtest=ModuleTest test
   - mvn -Dtest=StudentTest2 test
   - mvn -Dtest=CourseTest test
artifacts:
  paths:
      - target/surefire-reports/TEST-*.xml
  reports:
     junit:
       - target/surefire-reports/TEST-*.xml
  
on_success:
  stage: on_success
  script:
    - echo "Testing"
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  